import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const topics = [
  {
    name: "Technology",
    slug: "technology",
    subtopics: [
      { name: "Artificial Intelligence", slug: "artificial-intelligence" },
      { name: "Machine Learning", slug: "machine-learning" },
      { name: "Deep Learning", slug: "deep-learning" },
      { name: "Generative AI", slug: "generative-ai" },
      { name: "Large Language Models", slug: "large-language-models" },
      { name: "Cybersecurity", slug: "cybersecurity" },
      { name: "Hacking & Exploits", slug: "hacking-exploits" },
      { name: "Robotics", slug: "robotics" },
      { name: "Drones", slug: "drones" },
      { name: "Data Privacy", slug: "data-privacy" },
      { name: "Software Engineering", slug: "software-engineering" },
      { name: "Programming Languages", slug: "programming-languages" },
      { name: "Cloud Computing", slug: "cloud-computing" },
      { name: "DevOps & SRE", slug: "devops-sre" },
      { name: "Big Data", slug: "big-data" },
      { name: "Quantum Computing", slug: "quantum-computing" },
      { name: "Semiconductors", slug: "semiconductors" },
      { name: "Hardware", slug: "hardware" },
      { name: "Consumer Electronics", slug: "consumer-electronics" },
      { name: "Mobile Technology", slug: "mobile-technology" },
      { name: "AR & VR", slug: "ar-vr" },
      { name: "Metaverse", slug: "metaverse" },
      { name: "5G & Telecom", slug: "5g-telecom" },
      { name: "Internet Infrastructure", slug: "internet-infrastructure" },
    ],
  },
  {
    name: "Business & Economy",
    slug: "business-economy",
    subtopics: [
      { name: "Global Markets", slug: "global-markets" },
      { name: "Stock Market", slug: "stock-market" },
      { name: "IPOs", slug: "ipos" },
      { name: "Banking & Finance", slug: "banking-finance" },
      { name: "FinTech", slug: "fintech" },
      { name: "Startups", slug: "startups" },
      { name: "Unicorns", slug: "unicorns" },
      { name: "Venture Capital", slug: "venture-capital" },
      { name: "Mergers & Acquisitions", slug: "mergers-acquisitions" },
      { name: "Corporate Strategy", slug: "corporate-strategy" },
      { name: "Supply Chain", slug: "supply-chain" },
      { name: "Manufacturing", slug: "manufacturing" },
      { name: "Retail & E-Commerce", slug: "retail-ecommerce" },
      { name: "Real Estate", slug: "real-estate" },
      { name: "Energy Market", slug: "energy-market" },
      { name: "Oil & Gas", slug: "oil-gas" },
      { name: "Inflation", slug: "inflation" },
      { name: "Economic Indicators", slug: "economic-indicators" },
      { name: "Trade & Tariffs", slug: "trade-tariffs" },
      { name: "World Economy", slug: "world-economy" },
    ],
  },
  {
    name: "Science",
    slug: "science",
    subtopics: [
      { name: "Space & Astronomy", slug: "space-astronomy" },
      { name: "NASA & ISRO", slug: "nasa-isro" },
      { name: "Astrophysics", slug: "astrophysics" },
      { name: "Physics", slug: "physics" },
      { name: "Biology", slug: "biology" },
      { name: "Genetics", slug: "genetics" },
      { name: "Evolution", slug: "evolution" },
      { name: "Chemistry", slug: "chemistry" },
      { name: "Material Science", slug: "material-science" },
      { name: "Climate Science", slug: "climate-science" },
      { name: "Earth Science", slug: "earth-science" },
      { name: "Geology", slug: "geology" },
      { name: "Environmental Science", slug: "environmental-science" },
      { name: "Medical Research", slug: "medical-research" },
      { name: "Research & Innovation", slug: "research-innovation" },
    ],
  },
  {
    name: "Politics",
    slug: "politics",
    subtopics: [
      { name: "India Politics", slug: "india-politics" },
      { name: "US Politics", slug: "us-politics" },
      { name: "UK Politics", slug: "uk-politics" },
      { name: "EU Politics", slug: "eu-politics" },
      { name: "China Politics", slug: "china-politics" },
      { name: "Middle East Politics", slug: "middle-east-politics" },
      { name: "Global Politics", slug: "global-politics" },
      { name: "Public Policy", slug: "public-policy" },
      { name: "Legislation", slug: "legislation" },
      { name: "International Relations", slug: "international-relations" },
      { name: "Elections", slug: "elections" },
      { name: "Political Parties", slug: "political-parties" },
      { name: "Government Agencies", slug: "government-agencies" },
      { name: "Geopolitics", slug: "geopolitics" },
      { name: "Human Rights", slug: "human-rights" },
    ],
  },
  {
    name: "Crypto & Web3",
    slug: "crypto-web3",
    subtopics: [
      { name: "Bitcoin", slug: "bitcoin" },
      { name: "Ethereum", slug: "ethereum" },
      { name: "Altcoins", slug: "altcoins" },
      { name: "DeFi", slug: "defi" },
      { name: "NFTs", slug: "nfts" },
      { name: "Blockchain Technology", slug: "blockchain-technology" },
      { name: "Layer 2 Solutions", slug: "layer-2" },
      { name: "DAOs", slug: "daos" },
      { name: "Stablecoins", slug: "stablecoins" },
      { name: "Crypto Regulation", slug: "crypto-regulation" },
      { name: "Crypto Exchanges", slug: "crypto-exchanges" },
      { name: "Web3 Security", slug: "web3-security" },
      { name: "Mining & Staking", slug: "mining-staking" },
      { name: "Tokenomics", slug: "tokenomics" },
    ],
  },
  {
    name: "Entertainment",
    slug: "entertainment",
    subtopics: [
      { name: "Movies", slug: "movies" },
      { name: "TV Shows", slug: "tv-shows" },
      { name: "Web Series", slug: "web-series" },
      { name: "Celebrities", slug: "celebrities" },
      { name: "Music Industry", slug: "music-industry" },
      { name: "Streaming Platforms", slug: "streaming-platforms" },
      { name: "OTT Releases", slug: "ott-releases" },
      { name: "Gaming", slug: "gaming" },
      { name: "PC Gaming", slug: "pc-gaming" },
      { name: "Console Gaming", slug: "console-gaming" },
      { name: "Mobile Gaming", slug: "mobile-gaming" },
      { name: "Anime", slug: "anime" },
      { name: "K-Pop", slug: "k-pop" },
      { name: "Hollywood", slug: "hollywood" },
      { name: "Bollywood", slug: "bollywood" },
      { name: "Award Shows", slug: "award-shows" },
    ],
  },
  {
    name: "Sports",
    slug: "sports",
    subtopics: [
      { name: "Cricket", slug: "cricket" },
      { name: "IPL", slug: "ipl" },
      { name: "Football", slug: "football" },
      { name: "Premier League", slug: "premier-league" },
      { name: "La Liga", slug: "la-liga" },
      { name: "UEFA Champions League", slug: "champions-league" },
      { name: "F1", slug: "f1" },
      { name: "NBA", slug: "nba" },
      { name: "Tennis", slug: "tennis" },
      { name: "Olympics", slug: "olympics" },
      { name: "Boxing", slug: "boxing" },
      { name: "MMA / UFC", slug: "mma-ufc" },
      { name: "Badminton", slug: "badminton" },
      { name: "Esports", slug: "esports" },
      { name: "Chess", slug: "chess" },
    ],
  },
  {
    name: "Health & Lifestyle",
    slug: "health-lifestyle",
    subtopics: [
      { name: "Fitness", slug: "fitness" },
      { name: "Bodybuilding", slug: "bodybuilding" },
      { name: "Nutrition", slug: "nutrition" },
      { name: "Diet Trends", slug: "diet-trends" },
      { name: "Mental Health", slug: "mental-health" },
      { name: "Medicine", slug: "medicine" },
      { name: "Diseases & Conditions", slug: "diseases-conditions" },
      { name: "Medical Research", slug: "medical-research" },
      { name: "Wellness", slug: "wellness" },
      { name: "Sleep Science", slug: "sleep-science" },
      { name: "Yoga", slug: "yoga" },
      { name: "Meditation", slug: "meditation" },
      { name: "Biohacking", slug: "biohacking" },
      { name: "Lifestyle Trends", slug: "lifestyle-trends" },
    ],
  },
  {
    name: "Automobiles",
    slug: "automobiles",
    subtopics: [
      { name: "Electric Vehicles", slug: "electric-vehicles" },
      { name: "Tesla", slug: "tesla" },
      { name: "EV Charging Infra", slug: "charging-infrastructure" },
      { name: "Autonomous Vehicles", slug: "autonomous-vehicles" },
      { name: "Self-Driving Tech", slug: "self-driving" },
      { name: "Car Industry", slug: "car-industry" },
      { name: "Motorsports", slug: "motorsports" },
      { name: "Formula E", slug: "formula-e" },
      { name: "Two-Wheelers", slug: "two-wheelers" },
      { name: "Car Launches", slug: "car-launches" },
    ],
  },
  {
    name: "World Events",
    slug: "world-events",
    subtopics: [
      { name: "Wars", slug: "wars" },
      { name: "Conflicts", slug: "conflicts" },
      { name: "Military Movements", slug: "military-movements" },
      { name: "Terrorism", slug: "terrorism" },
      { name: "Natural Disasters", slug: "natural-disasters" },
      { name: "Earthquakes", slug: "earthquakes" },
      { name: "Floods", slug: "floods" },
      { name: "Hurricanes", slug: "hurricanes" },
      { name: "Wildfires", slug: "wildfires" },
      { name: "Diplomacy", slug: "diplomacy" },
      { name: "Peace Treaties", slug: "peace-treaties" },
      { name: "International Summits", slug: "international-summits" },
      { name: "Refugee Crises", slug: "refugee-crises" },
      { name: "Humanitarian Efforts", slug: "humanitarian-efforts" },
    ],
  },
  {
    name: "Environment",
    slug: "environment",
    subtopics: [
      { name: "Climate Change", slug: "climate-change" },
      { name: "Global Warming", slug: "global-warming" },
      { name: "Renewable Energy", slug: "renewable-energy" },
      { name: "Solar Energy", slug: "solar-energy" },
      { name: "Wind Energy", slug: "wind-energy" },
      { name: "Sustainability", slug: "sustainability" },
      { name: "Pollution", slug: "pollution" },
      { name: "Water Crisis", slug: "water-crisis" },
      { name: "Wildlife Conservation", slug: "wildlife-conservation" },
      { name: "Deforestation", slug: "deforestation" },
      { name: "Carbon Emissions", slug: "carbon-emissions" },
    ],
  },
  {
    name: "Education & Work",
    slug: "education-work",
    subtopics: [
      { name: "Careers", slug: "careers" },
      { name: "Hiring Trends", slug: "hiring-trends" },
      { name: "Job Market", slug: "job-market" },
      { name: "Remote Work", slug: "remote-work" },
      { name: "Workplace Culture", slug: "workplace-culture" },
      { name: "Skill Learning", slug: "skill-learning" },
      { name: "EdTech", slug: "edtech" },
      { name: "Online Courses", slug: "online-courses" },
      { name: "Productivity", slug: "productivity" },
      { name: "Leadership", slug: "leadership" },
      { name: "Internships", slug: "internships" },
      { name: "Tech Careers", slug: "tech-careers" },
      { name: "Work-Life Balance", slug: "work-life-balance" },
    ],
  },
];

async function main() {
  console.log("Starting seed...");

  for (const topic of topics) {
    const { subtopics, ...topicData } = topic;

    const createdTopic = await prisma.topic.create({
      data: {
        ...topicData,
        subTopics: {
          create: subtopics,
        },
      },
    });

    console.log(`Created topic: ${createdTopic.name} with ${subtopics.length} subtopics`);
  }

  console.log("Seed completed!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
