apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infonow

resources:
  - namespace.yaml
  - configmap.yaml
  - backend.yaml
  - frontend.yaml
  - ingestor.yaml
  - transformer.yaml
  - news-enricher.yaml
  - yt-enricher.yaml
  - ingress.yaml
